/** Quoting strategies for CSV fields containing special characters. */
export enum Quoting {
  MINIMAL,
  ALL,
  NON_NUMERIC,
  NONE,
}

/** Defines the properties of a particular dialect of CSV. */
export interface Dialect {
  delimiter: string;
  doubleQuote: boolean;
  escapeChar?: string;
  lineTerminator: string;
  quoteChar: string;
  quoting: Quoting;
  skipInitialSpace: boolean;
  strict: boolean;
}

/** Describes properties of comma-separated values generated by Excel. */
export const excel: Dialect = {
  delimiter: ',',
  doubleQuote: true,
  lineTerminator: '\r\n',
  quoteChar: '"',
  quoting: Quoting.MINIMAL,
  skipInitialSpace: false,
  strict: false,
};


/** Describes properties of tab-separated values generated by Excel. */
export const excelTab: Dialect = {
  delimiter: '\t',
  doubleQuote: true,
  lineTerminator: '\r\n',
  quoteChar: '"',
  quoting: Quoting.MINIMAL,
  skipInitialSpace: false,
  strict: false,
};


/** Describes properties of comma-separated values generated by Unix. */
export const unix: Dialect = {
  delimiter: ',',
  doubleQuote: true,
  lineTerminator: '\n',
  quoteChar: '"',
  quoting: Quoting.ALL,
  skipInitialSpace: false,
  strict: false
};
